{
   "jobs" : {
      "build" : {
         "environment" : {
            "CIRCLE_ARTIFACTS" : "/tmp/circle-artifacts"
         },
         "machine" : {
            "enabled" : true
         },
         "steps" : [
            "checkout",
            {
               "run" : {
                  "command" : "mkdir -p $CIRCLE_ARTIFACTS"
               }
            },
            {
               "run" : {
                  "command" : "docker info"
               }
            },
            {
               "run" : {
                  "background" : true,
                  "command" : "docker pull quay.io/wakaba/docker-perl-app-base"
               }
            },
            {
               "run" : {
                  "command" : "git clone https://bitbucket.org/wakabatan/swantenna repo"
               }
            },
            {
               "run" : {
                  "command" : "cd repo && git checkout -b radio origin/radio"
               }
            },
            {
               "run" : {
                  "command" : "cd repo && git submodule update --init"
               }
            },
            {
               "run" : {
                  "command" : "docker build -t quay.io/suikawiki/swantenna repo"
               }
            },
            {
               "run" : {
                  "command" : "mysql -u ubuntu circle_test \u003C repo/db/*.sql"
               }
            },
            {
               "run" : {
                  "command" : "ip route | awk '/docker0/ { print $NF }' > myip.txt"
               }
            },
            {
               "run" : {
                  "command" : "echo 'DBI:mysql:dbname=circle_test;host=dockerhost;user=ubuntu' > dsn.txt"
               }
            },
            {
               "run" : {
                  "command" : "echo '{\u0022dsns\u0022:{\u0022antenna\u0022:\u0022'`cat dsn.txt`'\u0022},\u0022alt_dsns\u0022:{\u0022master\u0022:{\u0022antenna\u0022:\u0022'`cat dsn.txt`'\u0022}}}' > config/config.json"
               }
            },
            {
               "run" : {
                  "command" : "docker run --name server -d -p 5511:8080 -e APP_CONFIG=/config/config.json -v `cd config && pwd`:/config --add-host=dockerhost:`cat myip.txt` quay.io/suikawiki/swantenna /server; sleep 10"
               }
            },
            {
               "run" : {
                  "command" : "#XXX curl -f http://localhost:5511/radio/"
               }
            },
            {
               "run" : {
                  "command" : "curl -f http://localhost:5511/radio/css"
               }
            },
            {
               "run" : {
                  "command" : "docker logs server"
               }
            },
            {
               "store_artifacts" : {
                  "path" : "/tmp/circle-artifacts"
               }
            },
            {
               "deploy" : {
                  "command" : "if [ \u0022${CIRCLE_BRANCH}\u0022 == 'antenna' ]; then\u000Atrue\u000Adocker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS quay.io\u000Afi"
               }
            },
            {
               "deploy" : {
                  "command" : "if [ \u0022${CIRCLE_BRANCH}\u0022 == 'antenna' ]; then\u000Atrue\u000Adocker push quay.io/suikawiki/swantenna\u000Afi"
               }
            }
         ]
      }
   },
   "version" : 2,
   "workflows" : {
      "build" : {
         "jobs" : [
            "build"
         ]
      },
      "version" : 2
   }
}
